### ISSUE TITLE
gitian: gitian-build.sh --setup complains if gitian.sigs etc already exist

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/docs#14]
```
fatal: destination path 'gitian.sigs' already exists and is not an empty directory.
fatal: destination path 'bitcoin-detached-sigs' already exists and is not an empty directory.
fatal: destination path 'gitian-builder' already exists and is not an empty directory.
```

This contradicts the clone instructions [here](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#installing-gitian).

**Comment by MarcoFalke** [comment]
Let me know if this is still an issue with the most recent version of gitian-build.py
