### ISSUE TITLE
gitian: invalid option: --detach-sign

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/docs#19]
```
Generating report
f0f58a3c4f262cd5d8ba91774f0c0ad643ca83c14a6a4991918f8a02c87fa483  bitcoin-0.16.0-aarch64-linux-gnu-debug.tar.gz
...
b801f1eeeb3ad4aeb7f1b58b91b8a382fe138399223430d8de4b790a4452918d  bitcoin-linux-0.16-res.yml
Done.
./bin/gsign:52:in `<main>': invalid option: --detach-sign (OptionParser::InvalidOption)
```

I got the same error last summer. The correct syntax on Debian seems to be `gsign -p true`

**Comment by Sjors** [comment]
Interestingly I only got this error when I ran `--setup` (see #9), whereas `./gitian-build.sh --detach-sign --no-commit -b sjors 0.16.0rc1` worked correctly. I suspect that I shouldn't have used the `-b` option during `--setup`, made a note there.

**Comment by MarcoFalke** [comment]
That thing should probably be rewritten to python

**Comment by Sjors** [comment]
That was with Debian 9. Not sure if related, but I don't get this error on Debian 8 with:

```sh
./gitian-build.sh --setup --detach-sign --no-commit -b sjors 0.16.0rc2
```

+1 for a Python rewrite, ideally with lots of checks for missing dependencies, misconfigured routes, etc.

**Comment by MarcoFalke** [comment]
Let me know if this is still an issue with the most recent version of gitian-build.py
