### ISSUE TITLE
gitian: add ntp instructions

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/docs#23]
If the VM clock is off by too much, you may get error messages, see [IRC log](https://botbot.me/freenode/bitcoin-core-dev/2018-02-08/?msg=96619084&page=3). 

cc @instagibbs

**Comment by laanwj** [comment]
So I guess the only part that needs a semi-accurate clock is downloading from https?

For the build itself it'd be a determinism leak if so.

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained for bitcoin-core, see #76
