### ISSUE TITLE
Interface name different from documentation

### ISSUE THREAD

**Issue by lvella** [bitcoin-core/docs#3]
Commands for creating the virtual interface on both distributions uses the name `br0`:

```
echo 'brctl addbr br0' >> /etc/rc.local
```

and

```
echo 'ifconfig br0 10.0.3.2/24 up' >> /etc/rc.local
```

But `gitian-build.sh` script looks instead for `lxcbr0`, not `br0`.

**Comment by MeshCollider** [comment]
Fixed in https://github.com/bitcoin/bitcoin/pull/11391
