### ISSUE TITLE
Move "reducing bitcoind memory usage" here?

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/docs#50]
I have a fairly popular gist on reducing bitcoind memory usage here: https://gist.github.com/laanwj/efe29c7661ce9b6620a7

Might make sense to move it here instead of maintaining it as a gist so that other people can contribute to it.

**Comment by MarcoFalke** [comment]
This is directly for end-users, so should be in the main git repo? Other stuff in this repo seems to be at least somewhat developer related.

**Comment by MarcoFalke** [comment]
See also
* https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-traffic.md

**Comment by jnewbery** [comment]
I agree with @MarcoFalke that this would be very helpful documentation in the main bitcoin/bitcoin repo.

**Comment by MarcoFalke** [comment]
We could also steal some of the info from here and put it in a doc: https://btcinformation.org/en/full-node

**Comment by fanquake** [comment]
I think I agree. If we're going to keep `reduce-traffic.md` in the main repo, then the memory gist could be added as `reduce-memory.md` etc.

**Comment by practicalswift** [comment]
+1 for making this excellent documentation easier to find by putting this in the main repo instead.

**Comment by fanquake** [comment]
Going to close this, as it's being added to the main repository in https://github.com/bitcoin/bitcoin/pull/16339.
