### ISSUE TITLE
bin/make-base-vm failing on Fedora

### ISSUE THREAD

**Issue by soeren-b-c** [bitcoin-core/docs#60]
Hi everyone

I'm trying to follow this guide about setting Fedora up for gitian building:

https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-fedora.md

but I keep running into problems with the proxy, and get errors like `Unable to connect to 172.17.0.1:3142:` when running the `bin/make-base-vm` command.

I have reported the issue with gitian here:

https://github.com/devrandom/gitian-builder/issues/227

but was thinking perhaps someone here could help with a solution?

I have tried different versions of Fedora and both installing docker through `dnf install` and the latest packages from docker.com, but with no luck.

Any ideas or hints appreciated.

Cheers

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained for bitcoin-core, see #76
