### ISSUE TITLE
MacOSX extraction needs to be updated for 10.14 and 10.15

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/docs#61]
Instructions [here](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-mac-os-sdk.md) only refer to 10.11.

There's instructions for 10.14 here
https://github.com/bitcoin/bitcoin/tree/0.20/contrib/macdeploy#sdk-extraction

For 10.15
https://github.com/bitcoin/bitcoin/tree/master/contrib/macdeploy#sdk-extraction

**Comment by elichai** [comment]
Should we delete https://github.com/bitcoin/bitcoin/blob/master/contrib/macdeploy/extract-osx-sdk.sh now that we're using https://github.com/bitcoin-core/apple-sdk-tools/blob/master/extract_xcode.py?

**Comment by justinmoon** [comment]
[extract-osx-sdk.sh](https://github.com/bitcoin/bitcoin/commit/1fbb8b6fa33e2a614689d7018ef146d68f78d236) was just removed by @hebasto

**Comment by laanwj** [comment]
@justinmoon Thanks! Yes, closing.
