### ISSUE TITLE
Package 'ubuntu-archive-keyring' has no installation candidate

### ISSUE THREAD

**Issue by pox** [bitcoin-core/docs#75]
When setting up gitian on Ubuntu 20.04 according to [this guide](https://github.com/bitcoin-core/docs/blame/master/gitian-building/gitian-building-setup-gitian-debian.md#L18) there's a dependency on a package called `ubuntu-archive-keyring` that seems to be gone.

```
$ sudo apt install ubuntu-archive-keyring
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ubuntu-archive-keyring is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ubuntu-archive-keyring' has no installation candidate
```

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained for bitcoin-core, see #76
