### ISSUE TITLE
Delete after gitian was removed?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/docs#76]
The repo can probably be wiped at some point.

**Comment by staktrace** [comment]
Yes please. I just spent some time reading through these docs only to discover the gitian-build.py file no longer exists. Trail of links I followed:
1. https://bitcoincore.org/en/download/
2. https://github.com/bitcoin-core/gitian.sigs
3. https://github.com/bitcoin-core/docs/blob/master/gitian-building.md

**Comment by fanquake** [comment]
> Trail of links I followed:
>  https://bitcoincore.org/en/download/

I've opened https://github.com/bitcoin-core/bitcoincore.org/pull/833 to address linking to guix.sigs instead of gitian.sigs.
